# Generated by Django 2.2.12 on 2022-09-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ImageField(upload_to='productimg/'),
        ),
    ]
