# Generated by Django 2.2.12 on 2022-09-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
